### PR TITLE
Button refactors 

### PR DESCRIPTION
**Pull request by phill-85**
See commit comments. 

You might want to pay attention specifically to lib.rs. use button::* was importing the Type enum that I added, but that was conflicting with the Type enum from annother module

### CODE REVIEW

**Comment by ctron** [comment]
Thanks for the contribution! I think it makes perfect sense!

I am just not happy about the new `Type` type, and the fact that this breaks the current pattern of the API. I am not saying that the API is the best idea, but just making a change for the `Button` type feels odd to me.

I think it should be possible to keep the current pattern (and reduce the impact) by just naming the type `ButtonType`. Not perfect, but also not too bad. What do you think?

**Comment by phill-85** [comment]
> I am just not happy about the new `Type` type, and the fact that this breaks the current pattern of the API. I am not saying that the API is the best idea, but just making a change for the `Button` type feels odd to me.

> I think it should be possible to keep the current pattern (and reduce the impact) by just naming the type `ButtonType`. Not perfect, but also not too bad. What do you think?

I just used alert.rs as an example. there is a "Type" enum there too. Perhaps that should be renamed too? I just wanted to get something in for you to have a look at. Personally I don't like use * but its up to you what you want...

So shall I rename alert::Type to alert::AlertTypr as well as button:Type to button::ButtonType?

**Comment by ctron** [comment]
I agree, this could structured differently, the question is just "how". And I think this needs more discussion.

However, I think that this PR should be about adding a new feature. So it shouldn't break existing code. Changing imports or renaming existing types would break the API.

So I would leave the existing `AlertType` as is, and just focus on the addition of the new functionality.

If you are interested, I would encourage you to create a new issue regarding the naming. And if you have ideas how to re-structure it, I would welcome your input.

**Comment by ctron** [comment]
Are you ok with merging it?

**Comment by phill-85** [comment]
> Are you ok with merging it?

I'm strugling with git to be honest. I dont have all that much experience with it.

**Comment by ctron** [comment]
> > Are you ok with merging it?
> 
> I'm strugling with git to be honest. I dont have all that much experience with it.

Don't worry. I would merge it. But I wanted to check with you if you think the PR is complete, and ready to be merged.

**Pull request merged**
